### ISSUE TITLE
Decoding in Arduino

### ISSUE THREAD

**Issue by cdupont** [ElectronicCats/CayenneLPP#18]
Hello, and thanks for this very useful library.
Is there any plan to add decoding in this library? This would be useful for downlink/actuation.

**Comment by sabas1080** [comment]
Hi @cdupont 

there are two examples that come with the library

example general:
https://github.com/ElectronicCats/CayenneLPP/tree/master/examples/Decode

and with TTN
https://github.com/ElectronicCats/CayenneLPP/blob/master/examples/DecodeTTN/DecodeTTN.ino

**Comment by cdupont** [comment]
Thanks, I asked a bit fast!
