### ISSUE TITLE
decoder: TheThingsStack v3 support

### ISSUE THREAD

**Issue by aparcar** [ElectronicCats/CayenneLPP#19]
The new stack uses a slightly different format, could you please update/add another decoder.js script to support v3?

https://www.thethingsindustries.com/docs/integrations/payload-formatters/javascript/

**Comment by sabas1080** [comment]
Hi @aparcar 
 
Welcome contribution :D

**Comment by amotl** [comment]
Hi Paul and Sabas,

while I am not that much into the very details, I would like to point out that @thiasB just added https://github.com/hiveeyes/terkin-datalogger/commit/71699ded to the [Terkin Datalogger](https://github.com/hiveeyes/terkin-datalogger).

In that manner, it might help to compare the implementations of [1] vs. [2], where [1] was already derived from this repository. By mentioning it, we want to take the chance to send a big thank you to @xoseperez, @ricaun and David, who we discovered to have committed to [`decoder.js`](https://github.com/ElectronicCats/CayenneLPP/blob/master/decoders/decoder.js).

Keep up the spirit and with kind regards,
Andreas.

[1] https://github.com/hiveeyes/terkin-datalogger/blob/master/client/TTN/decoder_v2.js
[2] https://github.com/hiveeyes/terkin-datalogger/blob/master/client/TTN/decoder_v3.js

**Comment by amotl** [comment]
Maybe you can also submit a pull request here, @thiasB?

**Comment by thiasB** [comment]
see https://github.com/ElectronicCats/CayenneLPP/pull/23

**Comment by sabas1080** [comment]
Thanks @amotl  and @thiasB
