### ISSUE TITLE
Please could you add litres/counter

### ISSUE THREAD

**Issue by Cloolalang** [ElectronicCats/CayenneLPP#21]
Please could you add litres/counter

**Comment by sabas1080** [comment]
Hi @Cloolalang 

You can use addDigitalInput or addDigitalOutput, or do you have a proposal of how it would be litres/counter?

**Comment by xoseperez** [comment]
CayeneLPP is based on the [IPSO smart objects specification](https://omaspecworks.org/wp-content/uploads/2018/03/ipso-paper.pdf). The original implementation only covers some of the "starter pack" objects (appendix 2). This library covers some more including some from the "expansion pack" (appendix 3) but still sticks to the original specification (using the objectID - 3200 as index).

There is no "volume" (the specification is quite limited). I also use the Digital Output for counters as @sabas1080 suggests. Of course a specific data type for volume could be added, there are a lot of unused indexes, but mind it will be out of spec.

**Comment by Cloolalang** [comment]
Hey, thanks for your replies, very interesting.
OK I see, digitalOut would work for me, I will decode using Node-red and rename the value there to litres for my application.
Thanks for improving this API with the extras! good job!
Is this the right one to use?:
node-red-contrib-cayennelpp-extended
Cheers
P
