### ISSUE TITLE
Update platformio lib version

### ISSUE THREAD

**Issue by aparcar** [ElectronicCats/CayenneLPP#26]
On platformio the latest release is still 1.1.0, please update it to 1.3.0...
https://platformio.org/lib/show/1767/CayenneLPP/installation

**Comment by sabas1080** [comment]
Hello @aparcar 

we did not request to platformio, pull request are welcome to update

**Comment by aparcar** [comment]
Are you saying you are not in touch with whoever maintains the current lib at platformio?

**Comment by sabas1080** [comment]
no, we do not publish on platformio

**Comment by aparcar** [comment]
This seems to have your username, are you sure it's not you? I can't seem to find the publisher if it wasn't you

**Comment by sabas1080** [comment]
we do not officially support our libraries in platformio, only arduino library manager

**Comment by aparcar** [comment]
All that's required to update the package is `pio package publish`, I've just did that and now version 1.3.0 is available. However I'd prefer you run the command and publish it under your own username, since you published version 1.1.0 in the past.

https://platformio.org/lib/show/12764/CayenneLPP

**Comment by sabas1080** [comment]
@aparcar Thanks!
