### ISSUE TITLE
Add pH sensor data type to the library

### ISSUE THREAD

**Issue by Hak4Kidz** [ElectronicCats/CayenneLPP#36]
Hi,

Helping a Scout work on his Eagle project to read temp and pH at a public golf courses irrigation ponds. I am trying to figure out how to add the data type to the CayenneLPP Arduino library. This [documentation](https://developers.mydevices.com/cayenne/docs/lora/#lora-cayenne-low-power-payload-examples-device-with-2-temperature-sensors) was kinda helpful, but doesn't speak exactly to what I need to do.

Looking for guidance on how to add a data type without breaking the library. 

Thanks!

**Comment by Hak4Kidz** [comment]
Looking inside the CayeneeLPP.h file and I was wondering if this project could use #define LPP_DIGITAL_INPUT to collect the pH sensor reading?

**Comment by sabas1080** [comment]
Yes, you can use addAnalogInput or addDgitalInput

**Comment by Hak4Kidz** [comment]
Thanks! I've already tested that and addAnalogInput is working. But the new issue is there is no trend information. We are looking to compare the pH and temperature over a period of time. Any thoughts on how to get that to work?

Thanks,
Heal
