### ISSUE TITLE
Feature Request: Be able to change feed name

### ISSUE THREAD

**Issue by hpssjellis** [ElectronicCats/CayenneLPP#38]
CayenneLPP seems to force the feed name. Can the feed name be changed in the sketch?

example

```
lpp.addDigitalInput(1, 0);
```

creates an MQTT feed called  ```Digital_Input```

Can that feed name be edited before it is sent?

**Comment by jazhe** [comment]
Hello @hpssjellis!
Thank you for your patience. Unfortunately, for now, is not possible to change or edit the name.
Apologies for the inconvenience caused.

**Comment by hpssjellis** [comment]
@jazhe No Problem, thanks for the reply. I wasn't sure if that was an easy change or not. Have a great day. Great library!
