### ISSUE TITLE
Enhancement: "businesslike conduct" round to reduce data error from 0.09 to 0.05 (~50% accuracy enhancement)

### ISSUE THREAD

**Issue by g6094199** [ElectronicCats/CayenneLPP#43]
hi,

we have seen some problems when it comes to rounding (in our case for temp measurements).

in the current code the float temp just gets cut after the 1st decimal place, which is very inaccurate!

` uint32_t v = value * multiplier;`

in this case the error is at worst 0.09. so almost 0.1° off.

instead the float temp should be businesslike conduct rounded (in germany we call this "Kaufmännisches Runden") before chopping off the last digit, like so:

` uint32_t v = round(value * multiplier);`

in this case the error is @ max. 0.05° off. which is much more accurate for professional use. of cause other values can benefit from this kind of correction, too.

**Comment by sabas1080** [comment]
for reference: https://github.com/ElectronicCats/CayenneLPP/issues/44#issuecomment-1594235566
