### ISSUE TITLE
GPS: add support for precision data

### ISSUE THREAD

**Issue by g6094199** [ElectronicCats/CayenneLPP#46]
Sometimes you need to know how accurate a GPS lock is, so it would be nice to have additional (optional) info for the gps signal

e.g TTNMapper:
The JSON object should contain the keys "latitude", "longitude" and "altitude" and **one of "hdop", "accuracy" or "sats"**. When using the Cayenne LPP data format, the GPS coordinates will be decoded into a different JSON format, but this format is also supported. Cayenne LPP does not contain a GPS accuracy, and therefore this data will be considered as inferior and will carry less weight in calculation of coverage, and will be deleted first during data cleanup.

[hdop](https://wiki.gopal-navigator.de/wiki/HDOP): decimal values up to 50 (float)
accuracy: ? this one i didnt get. in m? in %?
sats: up to 12 sattelites (Global Positioning System Fix Data (GGA) NN ) can be in sight. so int should do

**Comment by Eric286** [comment]
Hello @g6094199,

Thank you for your valuable feedback and suggestions regarding our CayenneLPP library. We greatly appreciate your input, and we understand the importance of having accurate GPS information in certain applications like TTNMapper.

Our team will carefully review your suggestions and discuss the possibility of implementing these enhancements in a future update. While we can't provide an estimated timeframe for when these changes might be incorporated, please rest assured that we are committed to continually improving our library to meet the needs of our users.

If you have any further insights or ideas in the future or if you encounter any issues while using our library, please don't hesitate to reach out. Your feedback helps us make our library better for everyone.

Thank you again for your contribution to the community, and we look forward to delivering an even more robust CayenneLPP library in the future.

Best regards,

Support Team.

**Comment by g6094199** [comment]
so we dont get pecision data?

**Comment by xoseperez** [comment]
I usually add these extra fields as analogOutput channels.
