### ISSUE TITLE
Adding new data types

### ISSUE THREAD

**Issue by xoseperez** [ElectronicCats/CayenneLPP#5]
I've been working on a fork of this repo to add new data types for:

* Generic Sensor
* Voltage
* Current
* Frequency
* Percentage
* Altitude
* Power
* Distance
* Energy
* Direction
* Switch

I have also added a unit test suite based on AUnit and a backwards compatible javascript decoder for TTN or NodeRED.

Everything is in the forked repo: https://github.com/xoseperez/CayenneLPP

The problem is that the code base is very different, including some files moved to subfolders to suit PlatformIO. The class itself is backwards compatible with this repo thou. My question is: should I keep it as a separate repo or would you be willing to accept a PR with the changes?

**Comment by sabas1080** [comment]
Hi @xoseperez 

Send your PR please, me and Wero we will review and add to this repository

Thanks for your work in espurna :D

**Comment by xoseperez** [comment]
Great. See PR #7 .
It includes data types suggested by @gmag11 in PR #4, I hope he doesn't mind.

**Comment by sabas1080** [comment]
Thanks @xoseperez merge

**Comment by xoseperez** [comment]
Great! Thank you.

**Comment by jangrewe** [comment]
I've started using this library and was pulling my hair why no data was showing up in Cayenne... turns out it doesn't like the data type `74` (from `addVoltage()`). Now i don't know the actual purpose of this library, but it should either be compatible with Cayenne, or mention somewhere which data types can't be used?

**Comment by sabas1080** [comment]
Hi @jangrewe the README mention that detail, we support most of the types specified by OMA SpecWorks, formerly IPSO

<img width="1048" alt="Captura de Pantalla 2020-07-30 a la(s) 20 35 50" src="https://user-images.githubusercontent.com/2874292/88990702-4efe9c80-d2a4-11ea-9c27-16a13a8cf202.png">

**Comment by jangrewe** [comment]
Well, for somebody just reading that it sounds like "we've added more stuff than anybody else. and we added a decoder".
May i suggest adding something explicit like "These additional data types are not supported by myDevices Cayenne."? 🙂

**Comment by xoseperez** [comment]
You can also ping the people at Cayenne and ask them to add these data types to their product :smile:

**Comment by sabas1080** [comment]
@jangrewe I have added the text 😀
