### ISSUE TITLE
Update PlatformIO libraries

### ISSUE THREAD

**Issue by dansiviter** [ElectronicCats/CayenneLPP#52]
**What idea or improvement for the library has occurred to you?**

**If you found an error:** 

Latest version PlatformIO knows about is 1.1.0. This library, at time of writing, is 1.4.0.

**Have you already found a solution?**

Workaround it to copy/paste he library directly into the project.

***Thanks a lot***

**Comment by Eric286** [comment]
Hello @dansiviter,

Could you please give me a little more context so I can document everything correctly and we can make this improvement in a better and faster way?

Have a nice day!

Kind Regards,

**Comment by dansiviter** [comment]
Hi @Eric286 

In the PlatformIO Registry, the latest version is 1.1.0: https://registry.platformio.org/libraries/sabas1080/CayenneLPP

Looking closer, it seems the ElectronicVats repo is referenced a, but the actual repository is from sabas1080. Therefore this might be that the library needs publishing directly from here rather than an intermediary. 

I hope that clears it up.

D

**Comment by Eric286** [comment]
Hello @dansiviter,

Thank you very much for the explanation, I will mention it to the team to verify and correct it.

Have a nice day!

Kind Regards,

**Comment by Eric286** [comment]
Hello @dansiviter,

I'm very sorry for the delay, but this has now been corrected. Thank you very much for informing us.
If you have any other questions or comments please send us a message again.

Have a nice day!

Kind Regards,
